services:
  - type: web
    name: myclient
    env: static
    buildCommand: npm run build
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: /api/*
        destination: https://myserver-egzl.onrender.com/api/*
      - type: rewrite
        source: /*
        destination: /index.html
      - type: rewrite
        source: /users
        destination: /index.html
      - type: rewrite
        source: /users/*
        destination: /index.html
